### ISSUE TITLE
Maintenance / Repo ownership

### ISSUE THREAD

**Issue by simonihmig** [kaliber5/ember-bootstrap-cp-validations#28]
Hey @offirgolan, it's been a while, hope you are all well! 😀

I have used my OSS friday to update things here, as this addon hasn't been touched for a while (3 years 😱). Wanted to drop support for old versions, make sure everything run with the latest ember-bootstrap, and some general maintenance stuff.

In the latter category I wanted to move CI to Github Actions (#25), but it seems the Travis CI check (which I wanted to replace) is set up in this repo to be required:

![image](https://user-images.githubusercontent.com/1325249/92234731-d8604a80-eeb2-11ea-888a-f53f672d30fb.png)

Thing is I don't have the required privileges here to change these settings. That brings up the question - given that as I said maintenance of this addon was a bit behind - whether you actually are still interested in ownership of this repo, and the maintenance burden related to it? :)

So either giving me administration rights here would make me able to continue maintaining this without bothering you. Or if you are not at all interesting in keeping this repo, would you consider transferring ownership to me?

**Comment by offirgolan** [comment]
Hi @simonihmig, its been way too long. I've been good... as good as can be during these times. I hope you are doing well also!  

Thanks for taking the time to update this repo, I can't believe its been 3 years lol. I'm not seeing any way of giving you admin access to the repo but I can definitely transfer it over to you. For me to do that, you'd need to delete the fork you have on your account.

**Comment by simonihmig** [comment]
> For me to do that, you'd need to delete the fork you have on your account.

I just did that. Thanks @offirgolan!

**Comment by simonihmig** [comment]
Thanks @offirgolan, just moved the repo. That makes it much easier. Especially publishing a new release (which I just had to do), as previously I could not directly push to master a release commit. Take care!
